import React from "react";

const Terms = () => {
  return (
    <main className="mx-auto w-full lg:max-w-7xl grid space-y-6 lg:my-6">
      <div className="text-center flex flex-col text-white space-y-4 lg:my-12 my-4">
        <h1 className="font-onest font-semibold text-3xl lg:text-[78px] leading-tight tracking-tight ">
          Terms Of Services
        </h1>
        <p className="font-figtree font-light text-sm lg:text-lg leading-tight">
          Last Updated February, 2025
        </p>
      </div>
      <div className="grid items-center bg-white rounded-2xl lg:rounded-[32px] p-8 lg:p-16 space-y-4">
        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light">
          <p>
            Monjin Interviews Private Limited, including its subsidiaries,
            affiliates and licensors (collectively “Monjin”, “Company”, “we”,
            “us” or “our”) welcomes you (the “Client”, “user”, “you” or “your”)
            to www.monjin.com (or any replacement or successor domain name) (the
            “Website”). <br />
            <br />
            These terms of use, together with: (i) the Company&apos;s Privacy
            Policy; (ii) the guidelines, rules, policies and procedures posted
            on the Website, from time to time (each of which is incorporated
            herein by reference and form an integral part of these terms); and
            (iii) any other agreements and terms and conditions entered into
            with Company, including offline agreements (collectively “Terms of
            Service”) govern: (i) your relationship with Company; (ii) your use
            of the Website; and (iii) the content, features, applications,
            tools, data, documents and information available through the
            Website, and/or through Company (together with the Website, the
            “Services”).
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Terms of Service
          </h2>
          <p>
            Monjin Interviews Private Limited, including its subsidiaries,
            affiliates and licensors (collectively “Monjin”, “Company”, “we”,
            “us” or “our”) welcomes you (the “Client”, “user”, “you” or “your”)
            to www.monjin.com (or any replacement or successor domain name) (the
            “Website”). <br />
            <br />
            Please read these Terms of Service carefully before using the
            Services. These Terms of Service apply to all users of the Services,
            irrespective of the mode and the manner in which they have accessed
            the Services. <br />
            <br />
            These Terms of Service constitute an electronic record within the
            meaning of applicable law. This electronic record is generated by a
            computer system and does not require any physical or digital
            signatures. These Terms of Service are published in compliance of,
            and is governed by the provisions of Indian law, including but not
            limited to: (i) the Indian Contract Act, 1872; and (ii) the (Indian)
            Information Technology Act, 2000 and the rules, regulations,
            guidelines and clarifications framed there under, including the
            (Indian) Information Technology (Reasonable Security Practices and
            Procedures and Sensitive Personal Information) Rules, 2011 and the
            (Indian) Information Technology (Intermediaries Guidelines) Rules,
            2011. <br />
            <br />
            If you are using the Services on behalf of an entity, company or
            other organization, you represent and warrant that you: <br />
            (i) have the authority to bind such entity, company or organization
            to these Terms of Service; and <br />
            (ii) agree to be bound by these Terms of Service on behalf of such
            entity, company or organization. <br />
            If you are using the Services on behalf of any other person (whether
            under his authority or otherwise), you represent and warrant that
            you:
            <br />
            (i) have the authority to bind such person to these Terms of
            Service\; and <br />
            (ii) agree to be bound by these Terms of Service on behalf of such
            person. <br /> <br />
            Accessing, browsing or using the Website, agreeing to use the
            Services, ordering the Services on the Website, engaging in any
            transaction with respect to the Services, or ordering the Services
            from the Company, constitutes your unconditional acceptance and
            agreement to be bound by these Terms of Service, which may be
            modified by us, at any time and from time to time, without notice to
            you. <br />
            <br />
            Monjin reserves the right, at any time and from time to time, to
            amend, modify, revise, update, suspend, remove and/or otherwise
            change the Terms of Service without prior notice to you, provided
            that if any such alterations constitute a material change to these
            Terms of Service, Monjin will notify you by posting an announcement
            on the Website. All such amendments and modifications shall take
            effect immediately when posted on the Website. By continuing to
            access the Website or use the Services after any such amendments or
            modifications, you agree to be bound by such amended or modified
            Terms of Service. For this reason, we encourage you to review the
            Terms of Service whenever you use the Services. If you do not agree
            to any change to these Terms of Services, then you must immediately
            stop using the Services.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Privacy Statement
          </h2>
          <p>
            By using our Website or purchasing/utilizing our Services, you agree
            that we may use and share your personal information in accordance
            with the terms of our Privacy Policy. We are committed to protecting
            your privacy. We constantly review our systems and data to ensure
            the best possible service to our customers and you. Refer our
            Privacy Policy for details.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Use of Website & Services
          </h2>
          <p>
            You shall use the Website only for lawful purposes for evaluating
            potential job applicants for job vacancies with You, in your company
            / affiliated company / companies / your client(s). <br />
            <br />
            You shall not (directly or indirectly): <br />
            (i) use the Website or the Service in violation of any law, rule or
            regulation or otherwise in violation of any law, rule or regulation
            which you may be subject to; <br />
            (ii) use the Service for any fraudulent or unlawful purpose or for
            the promotion of illegal activities; <br />
            (iii) use the Services if you are a competitor of the Company or for
            reasons that are in competition with the Company; <br />
            (iv) use the Services, its content or its features and services in
            any manner that could interrupt, damage, disable, overburden or
            impair the Services or interfere with any other persons use and
            enjoyment of the Services; <br />
            (v) bypass, circumvent or attempt to bypass or circumvent any
            measures we may use to prevent or restrict access to the Services
            (or other accounts, computer systems or networks connected to the
            Services); <br />
            (vi) obtain or attempt to gain unauthorized access to other computer
            systems, materials, information or any services available on or
            through the Website through any means, including through means not
            intentionally made publically available or provided for through the
            Website; <br />
            (vii) take any action that imposes or may impose (as determined by
            us in our sole discretion) an unreasonable or disproportionately
            large load on our (or our third party service providers&apos;)
            infrastructure; <br />
            (viii) interfere or attempt to interfere with the proper working of
            the Website and Services or any activities conducted on the Website;
            and <br />
            (ix) use the Services offered in any manner so as to impair the
            rights and interests of Monjin. <br />
            <br />
            You shall use the Website solely for your own needs. Using the
            content, information, data, text, software, scripts, graphics, audio
            and video content and interactive features generated, provided, or
            otherwise made accessible on or through the Services (collectively
            “Content”) for creating derivative works with a commercial motive
            without the prior written consent from Monjin is strictly
            prohibited. <br />
            <br />
            You shall not sell, transfer or modify any Content, any official
            documents, and candidates’ personal documents made available to you
            through the Website or reproduce, display, publicly perform,
            distribute, and/or otherwise use them in any way for any public or
            commercial purpose, or for any purpose other than that for which
            they are shared with you. <br />
            <br />
            You shall not copy or adapt the HTML code that Monjin creates to
            generate any Content on the Website. Nothing in these Terms of
            Service shall be construed as conferring any license to intellectual
            property rights of Monjin, whether by estoppel, implication or
            otherwise. <br />
            <br />
            Should any of the content made available to you through the Website
            be copied, leaked, or reproduced either in its original format or in
            an edited format, Monjin shall exercise its right to trace the
            source from where such act resulting in the breach of these Terms of
            Services originated, and shall take legal action as per applicable
            law. You will be held liable for the safety and privacy or misuse of
            any and all of this content. <br />
            <br />
            You hereby agree that in case of breach of these Terms of Service by
            any individual within your organization acting on his own accord and
            having gained access to Monjin’s Website and its content through his
            employment with You / Your company, both such individual and You /
            Your company shall be held jointly and severally liable for such
            breach and shall be subjected to civil and/or criminal action.
            Monjin, its subsidiaries, affiliates, and their respective officers,
            directors, employees and agents, shall NOT be held responsible in
            any manner for the consequences arising from such breach. <br />
            <br />
            Violation by You of these Terms of Service gives Monjin the right to
            deny You access to the Website and the Services. In such case,
            Monjin may choose to either suspend or terminate your use of the
            Website and the Services, and such choice shall be at Monjin&apos;s
            absolute discretion. <br />
            <br />
            Content <br />
            All content created, added, uploaded, submitted, distributed,
            communicated or posted on the Website by users (collectively “User
            Content”), whether publicly posted or privately transmitted, is the
            sole responsibility of the user/person who originated such User
            Content. The Website permits the submission of User Content and the
            hosting, sharing, and/or publishing of such User Content.
            Notwithstanding anything contained herein, the user shall be solely
            responsible for user&apos;s own User Content and the consequences of
            posting or publishing them. You represent that all User Content
            provided by you is accurate, complete, up-to-date, and in compliance
            with all applicable laws, rules and regulations. You acknowledge
            that all content on the Website, including User Content, accessed by
            you using the Services, is at your own risk and you will be solely
            responsible for any damage or loss to you or any other party
            resulting therefrom. The Company does not and will not claim any
            ownership over or rights to User Content other than a license to use
            and display it in terms hereof. <br />
            <br />
            In connection with the User Content, user affirms, represents,
            and/or warrants that: <br />
            (i) user owns or has the necessary licenses, rights, consents,
            permissions and authorizations to use and authorize Company to use,
            all User Content, including to enable Company to include and use the
            User Content for the purposes and in the manner contemplated by
            these Terms of Service; and <br />
            (ii) the Company will not be subjected to any claim, actions,
            liabilities, loss and damage as a result of its use of the User
            Content. <br />
            By submitting any User Content to the Website, you hereby do and
            shall grant us a worldwide, non-exclusive, perpetual, irrevocable,
            royalty-free, fully paid, sub-licensable and transferable license to
            use, aggregate, reproduce, distribute, prepare derivative works of,
            display, perform, and otherwise fully exploit such User Content in
            connection with the Website, the Services and our (and our
            successors&apos; and assigns&apos;) businesses, including without
            limitation for promoting and redistributing, part or all of the
            Website or the Services (and derivative works thereof) in any media
            formats and through any media channels (including, without
            limitation, third party websites and feeds), and including after
            your termination of the Services. <br />
            <br />
            The Company: <br />
            (i) cannot control the User Content and other information provided
            by users which is made available on the Website; <br />
            (ii) does not research, endorse, validate or certify the User
            Content (as defined below) and any other information
            submitted/uploaded by users on the Website nor assumes that all User
            Content and information will be complete, accurate, truthful,
            trustworthy and reliable; and <br />
            (iii) expressly disclaims any and all liability in connection with
            User Content. <br />
            <br />
            The Services may contain content specifically provided by us, our
            partners or our users and such content is protected by copyrights,
            trademarks, service marks, patents, trade secrets or other
            proprietary and intellectual property rights and laws. You shall
            abide by and maintain all copyright notices, information, and
            restrictions contained in any content accessed through the Services.{" "}
            <br />
            <br />
            As mandated by Regulation 3(2) of the Information Technology
            (Intermediaries Guidelines) Rules, 2011, the Company hereby informs
            users that they are not permitted to host, display, upload, modify,
            publish, transmit, update or share any information that: <br />
            (i) belongs to another person and to which the user does not have
            any right to; <br />
            (ii) is grossly harmful, harassing, blasphemous, defamatory,
            obscene, pornographic, pedophilic, libelous, invasive of
            another&apos;s privacy, hateful, or racially, ethnically
            objectionable, disparaging, relating or encouraging money laundering
            or gambling, or otherwise unlawful in any manner whatever; <br />
            (iii) harm minors in any way; <br />
            (iv) infringes any patent, trademark, copyright or other proprietary
            rights; <br />
            (v) violates any law for the time being in force; <br />
            (vi) deceives or misleads the addressee about the origin of such
            messages or communicates any information which is grossly offensive
            or menacing in nature; <br />
            (vii) impersonate another person; <br />
            (viii) contains software viruses or any other computer code, files
            or programs designed to interrupt, destroy or limit the
            functionality of any computer resource; and <br />
            (ix) threatens the unity, integrity, defence, security or
            sovereignty of India, friendly relations with foreign states, or
            public order or causes incitement to the commission of any
            cognisable offence or prevents investigation of any offence or is
            insulting any other nation.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Termination of Agreements
          </h2>
          <p>
            The Company reserves the right, in its sole discretion, to terminate
            your access to all or any part of the Services at any time, with or
            without notice, effective immediately, including but not limited to
            as a result of your violation of any of these Terms of Service.{" "}
            <br />
            <br />
            Both the Client and we have the right to terminate any services
            agreement for any reason, including the ending of services that are
            already underway. No refunds shall be offered, where a Service is
            deemed to have begun and is, for all intents and purposes, underway.
            Any monies that have been paid to us which constitute payment in
            respect of the provision of unused Services shall be refunded.{" "}
            <br />
            <br />
            Any user may terminate these Terms of Service at any time by ceasing
            all use of the Services. All provisions of these Terms of Service
            which by their nature should survive termination shall survive
            termination, including, without limitation, licenses of User
            Content, ownership provisions, warranty disclaimers, indemnity and
            limitation of liability.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">Log Files</h2>
          <p>
            We use IP addresses to analyse trends, administer the site, track
            user’s movement, and gather broad demographic information for
            aggregate use. IP addresses are not linked to personally
            identifiable information. Additionally, for systems administration,
            detecting usage patterns and troubleshooting purposes, our web
            servers automatically log standard access information including
            browser type, access times/open mail, URL requested, and referral
            URL. This information is not shared with third parties and is used
            only within the Company on a need-to-know basis. Any individually
            identifiable information related to this data will never be used in
            any way different to that stated above without your explicit
            permission.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">Cookies</h2>
          <p>
            Like most interactive web sites, the Website uses cookies to enable
            us to retrieve user details for each visit. Cookies are used in some
            areas of our Website to enable the functionality of this area and
            ease of use for those people visiting. Some of our affiliate
            partners may also use cookies. Refer our Privacy Policy for details
            of how we use cookies.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Links to a Website
          </h2>
          <p>
            You shall not create a link to any page of this Website without our
            prior written consent.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Links from a Website
          </h2>
          <p>
            We do not monitor or review the content of other party&apos;s
            websites which are linked to from the Website. Opinions expressed or
            material appearing on such websites are not necessarily shared or
            endorsed by us and we should not be regarded as the publisher of
            such opinions or material. Please be aware that we are not
            responsible for the privacy practices, or content, of these sites.
            We encourage our users to be aware when they leave our site and to
            read the privacy statements of these sites. You should evaluate the
            security and trustworthiness of any other site connected to this
            site or accessed through this site yourself, before disclosing any
            personal information to them. The Company will not accept any
            responsibility for any loss or damage in whatever manner, howsoever
            caused, resulting from your disclosure to third parties of personal
            information.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Intellectual Property & Copyright Notice
          </h2>
          <p>
            The Website and all information and Content available on the Website
            and its “look and feel”, except User Content (as defined herein),
            including but not limited to trademarks, logos, service mark,
            copyrighted works, text, graphics, logos, button icons, images,
            audio/video clips, data complications and software, and the
            compilation and organization thereof is the property of the Company,
            its affiliates, partners or licensors, or is used with consent of
            the owner and is protected by laws, including laws governing
            copyrights and trademarks. The reproduction and use of any of these
            by you is prohibited unless specific written permission is provided
            by us. Any unauthorized use shall violate copyright laws, trademark
            laws, privacy and publicity laws, and/or communication regulation.{" "}
            <br />
            <br />
            The Website contains valuable trademarks, service marks, names,
            titles, logos, images, designs, copyrights and other proprietary
            materials owned, registered and used by the Company, including but
            not limited to, the mark “Monjin” (collectively, “Company&apos;s
            Marks”). The Company&apos;s Marks are the intellectual property
            rights of the Company. Any unauthorized use of the same is strictly
            prohibited and all rights in same are reserved by the Company. No
            use of any the Company’s Marks may be made by any third party
            without express written consent of the Company. <br />
            <br />
            You agree not to engage in the use, copying, or distribution of any
            of the content of the Website other than expressly permitted herein,
            including any use, copying, or distribution of Content obtained
            through the Website for any commercial purposes. If you download or
            print any Content for personal use, you must retain all copyright
            and other proprietary notice contained therein. <br />
            <br />
            Nothing contained on this Website should be construed as granting,
            by implication or otherwise, any right, license or title to any of
            the Company’s intellectual property and the Company’s Marks, without
            the prior written permission of the Company. All rights are
            expressly reserved and retained by the Company. Your misuse of any
            of the Company’s Marks displayed on the Website, or any other
            Content on the Website, except as provided in these Terms of
            Service, is strictly prohibited. You are also advised that the
            Company considers its intellectual property to be among its most
            valuable assets and will aggressively enforce its intellectual
            property rights to the fullest extent of the law.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Communication
          </h2>
          <p>
            When you use the Website and Services or send emails or other data,
            information or communication to us, you agree and understand that
            you are communicating with us through electronic records and you
            consent to receive communications via electronic records from us
            periodically and as and when required. We reserve the right to
            communicate with you by email or by such other mode of
            communication, electronic or otherwise. We may use a third party
            platform for making calls for matters related to the services being
            provided by Monjin and these calls shall be made notwithstanding
            your DND status. <br />
            <br />
            We have several different e-mail addresses for different queries.
            These, and other contact information, can be found on our About Us
            link on our Website or via the Company’s literature or via the
            Company’s stated telephone, facsimile or mobile telephone numbers.
            The Company is registered in India and its registered address is
            Survey no. 286/1B/2, Pallod Farms 3 Baner, Pune – 411045 (MAH)
            India.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Governing Law & Jurisdiction
          </h2>
          <p>
            These Terms of Service will be governed by the laws of India.
            Further, the courts at Pune, India shall have exclusive jurisdiction
            for all matters arising out of or in connection with these Terms of
            Service and you agree to irrevocably submit to the exclusive
            jurisdiction of such courts.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Force majeure
          </h2>
          <p>
            The Company shall be liable to the user for any failure to perform
            any obligation under these Terms of Service or any agreement which
            is due to an event beyond the control of the Company including but
            not limited to any act of God, terrorism, war, political insurgence,
            insurrection, riot, civil unrest, act of civil or military
            authority, uprising, earthquake, flood, change in law, or any other
            natural or man made eventuality outside of the Company&apos;s
            control.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Entire Agreement
          </h2>
          <p>
            These Terms of Service, including all related agreement and policies
            incorporated by reference herein, constitutes the entire agreement
            between you and the Company related to the subject matter hereof.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Severability
          </h2>
          <p>
            If any provision of these Terms of Service are deemed invalid or
            unenforceable for any reason (including, but not limited to the
            exclusions and limitations set out above), then the invalid or
            unenforceable provision will be severed from these terms and the
            remaining terms will continue to apply.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">Waiver</h2>
          <p>
            Failure of the Company to enforce any of the provisions set out in
            these Terms of Service and any other agreement, or failure to
            exercise any option to terminate, shall not be construed as waiver
            of such provisions and shall not affect the validity of these Terms
            of Service or of any other agreement or any part thereof, or the
            right thereafter to enforce each and every provision.
          </p>
        </div>

        <div className="font-figtree text-sm lg:text-lg font-normal lg:font-light mb-4">
          <h2 className="fonr-onest font-semibold text-2xl mb-4">
            Notification of Changes
          </h2>
          <p>
            The Company reserves the right to change these Terms of Service from
            time to time as it deems fit and your continued use of the Website
            will signify your acceptance of any changes to these terms. If there
            are any changes to our privacy policy, we will announce that these
            changes have been made on our home page and on other key pages on
            our Website. You are therefore advised to re-read this statement on
            a regular basis. <br />
            <br />
            These Terms of Service form part of the agreement between the Client
            and Monjin. Your accessing of the Website and/or undertaking of a
            booking or agreement indicates your understanding, agreement to and
            acceptance, of the Disclaimer Notice and the full Terms of Service
            contained herein. Specific to our Clients, the service agreement
            signed between Monjin and the Client will supersede these Terms of
            Service wherever there are conflicts.
          </p>
        </div>

        <div className="font-figtree lg:font-light lg:text-lg text-sm">
          <p className="text-right">
            © 2018 Monjin Interviews Pvt. Ltd. All Rights Reserved.
          </p>
        </div>
      </div>
    </main>
  );
};

export default Terms;
